### ISSUE TITLE
searchEngine feature pulls scrapes very low amount of usernames

### ISSUE THREAD

**Issue by a7t0fwa7** [nodauf/GoMapEnum#1]
Hey there! currently testing out your tool as it looks practical for my OSINT workflow, however i have noticed that when using the 'searchEngine' function it pulls in a very low amount of usernames compared to CrossLinked which i used as a benchmark, 
![image](https://user-images.githubusercontent.com/43460290/145980107-1b10fe2a-cf3d-4a0f-b588-5a6537e7c24d.png)

Whereas CrossLinked got me 246 on the first batch
![image](https://user-images.githubusercontent.com/43460290/145981211-685d36a7-4122-405b-a398-b0933b93764c.png)
![image](https://user-images.githubusercontent.com/43460290/145981394-34796a1e-6393-41eb-a56e-3f22e0341e5a.png)

Could this be due to parsing issues ?

PS: In the CrossLinked screenshot the tool did not find any emails on the other search engines i had asked it to search on so only Google and Bing came up with data

Many thanks

**Comment by nodauf** [comment]
Hi,
Thank you for the feedback. I'll look into it when I have some free time.

**Comment by a7t0fwa7** [comment]
No problems!

**Comment by nodauf** [comment]
Could you test with the last release?
Few improvements have been done to the search engine module

**Comment by a7t0fwa7** [comment]
> Could you test with the last release? Few improvements have been done to the search engine module

Sure will retest and let you know

**Comment by nodauf** [comment]
I am closing this issue. Feel free to open it if you still see major differences with CrossLinked
