### ISSUE TITLE
Teams Enumeration Error

### ISSUE THREAD

**Issue by Virgilsoeas** [nodauf/GoMapEnum#10]
Command:
go run main.go teams userenum -t "ey.... the whole token provided" -u Usernames.txt --verbose 

Enumeration		Teams				The token may be invalid or expired. The status code returned by the server is 401

I'm currently using the bearer token from https://developer.microsoft.com/en-us/graph/graph-explorer. I was wondering if others are having this issue?

**Comment by nodauf** [comment]
Hi,
This is not the same token.  The easiest way to get the JWT token is to authenticate on https://teams.microsoft.com/, search for a user externally through the search bar on the top and see the JWT token in the request made to https://teams.microsoft.com/api/mt/emea/beta/users/...

You can also find the token in the cookie authtoken between the `Bearer%3D` and `%26Origin`

Note that the token must start with `eyJ0eXAi...`

**Comment by Virgilsoeas** [comment]
Perfect! Thank you very much
