### ISSUE TITLE
False flag

### ISSUE THREAD

**Issue by vysecurity** [nodauf/GoMapEnum#3]
How does one pass a False flag into any parameter?

I can't get it to stop trying on lockout.

**Comment by vysecurity** [comment]
Oh got it. Let me try that.

**Comment by nodauf** [comment]
Ok let met check. It's for o365?

**Comment by vysecurity** [comment]
Yep exactly.

**Comment by nodauf** [comment]
Do you use the main banch or the last release?

**Comment by vysecurity** [comment]
Main branch.

**Comment by vysecurity** [comment]
I'll test it again tomorrow.

**Comment by nodauf** [comment]
Was you able to test it?

**Comment by vysecurity** [comment]
Yep, though sometimes the whole thing stops due to a Microsoft error. Aside from that it works as intended.

**Comment by nodauf** [comment]
What is the Microsoft error?

**Comment by vysecurity** [comment]
Ah no problem.
