### ISSUE TITLE
issue with Go

### ISSUE THREAD

**Issue by 0fux** [nodauf/GoMapEnum#7]
hi, gomapenum was working fine for me a few months ago but seems like maybe an update to go or kali has caused this new error. I'm attempting the linkedin functionality and it returns this.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x80ed59]

goroutine 1 [running]:
GoMapEnum/src/modules/linkedin.(*Options).getCompanyInfo(_)
        /root/GoMapEnum/src/modules/linkedin/utils.go:29 +0x3f9
GoMapEnum/src/modules/linkedin.(*Options).Gather(0xda7100)
        /root/GoMapEnum/src/modules/linkedin/gather.go:61 +0x885
GoMapEnum/src/cmd/linkedin.glob..func2(0xcdeb80?, {0x9167d8?, 0x9?, 0x9?})
        /root/GoMapEnum/src/cmd/linkedin/gather.go:31 +0x125
github.com/spf13/cobra.(*Command).execute(0xcdeb80, {0xc00015e120, 0x9, 0x9})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xcdc060)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
GoMapEnum/src/cmd.Execute()
        /root/GoMapEnum/src/cmd/root.go:31 +0x25
main.main()
        /root/GoMapEnum/src/main.go:21 +0x17
exit status 2

I'm using go version go1.19.8 linux/amd64, and using the latest version of kali. Not too familiar with Go so not sure how to proceed-- any ideas how I should move forward?

**Comment by nodauf** [comment]
Hi,
Could you try with the last commit?

**Comment by nodauf** [comment]
After your issue, I pushed a new commit that should fix it. When LinkedIn returns a status code different than 200, the program was crashing by trying to display an error.

**Comment by 0fux** [comment]
just tried and seems like that fixed the crashing error. but now it shows "Error: something went wrong. Status code 404 != 200"
I wonder why linkedin isn't resolving? the li_at cookie and everything is correct

**Comment by nodauf** [comment]
It should be fixed with the last commit. 
btw If you know the LinkedIn ID of the company (go on the profile page of the company and click on **people working here**, in the URL you will see the pattern **currentCompany=%5B"** then followed by an ID) you can use it with the option *-i*

For example for the company Contoso (https://www.linkedin.com/search/results/people/?currentCompany=%5B%2211452158%22%5D) the id is 11452158
